// src/bot/utils/localization.js
const languages = {
    en: {
      welcome: "Welcome to GhostTrail 👻",
      home: "🏠 Home",
      portfolio: "💼 Portfolio",
      explore: "🔎 Explore",
      transfer: "💸 Transfer",
      error: "❗ Oops, something went wrong.",
      withdrawal_success: "✅ Withdrawal Successful!",
      choose_currency: "Choose your currency",
      enter_address: "Enter destination address",
      enter_amount: "Enter amount to send",
      send_receipt: "Send proof receipt (QR code)",
      no_transactions: "No transactions found yet.",
      home_menu:             "What would you like to do?",
      no_addresses:          "You have no deposit addresses yet.",
      your_addresses_count:  "You have {{count}} deposit address(es):",
      select_address_delete: "Select one to delete:",
      address_deleted:       "✅ Address deleted.",
    },
    zh: {
      welcome: "欢迎来到 GhostTrail 👻",
      home: "🏠 主页",
      portfolio: "💼 投资组合",
      explore: "🔎 浏览",
      transfer: "💸 转账",
      error: "❗ 出错了，请稍后再试。",
      withdrawal_success: "✅ 提现成功！",
      choose_currency: "选择您的货币",
      enter_address: "输入收款地址",
      enter_amount: "输入发送金额",
      send_receipt: "发送收据证明（二维码）",
      no_transactions: "暂无交易记录。",
      home_menu:             "您想做什么？",
      no_addresses:          "您还没有存款地址。",
      your_addresses_count:  "您有 {{count}} 个存款地址：",
      select_address_delete: "请选择一个要删除：",
      address_deleted:       "✅ 地址已删除。",
    },
    vi: {
      welcome: "Chào mừng đến với GhostTrail 👻",
      home: "🏠 Trang chủ",
      portfolio: "💼 Danh mục đầu tư",
      explore: "🔎 Khám phá",
      transfer: "💸 Chuyển khoản",
      error: "❗ Đã xảy ra lỗi, vui lòng thử lại.",
      withdrawal_success: "✅ Rút tiền thành công!",
      choose_currency: "Chọn loại tiền tệ",
      enter_address: "Nhập địa chỉ người nhận",
      enter_amount: "Nhập số tiền cần gửi",
      send_receipt: "Gửi biên lai bằng mã QR",
      no_transactions: "Chưa có giao dịch nào.",
      home_menu:             "Bạn muốn làm gì?",
      no_addresses:          "Bạn chưa có địa chỉ nạp nào.",
      your_addresses_count:  "Bạn có {{count}} địa chỉ nạp:",
      select_address_delete: "Chọn địa chỉ để xóa:",
      address_deleted:       "✅ Đã xóa địa chỉ.",
    },
    th: {
      welcome: "ยินดีต้อนรับสู่ GhostTrail 👻",
      home: "🏠 หน้าแรก",
      portfolio: "💼 พอร์ตการลงทุน",
      explore: "🔎 สำรวจ",
      transfer: "💸 โอนเงิน",
      error: "❗ เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง",
      withdrawal_success: "✅ ถอนเงินสำเร็จ!",
      choose_currency: "เลือกสกุลเงิน",
      enter_address: "กรอกที่อยู่ปลายทาง",
      enter_amount: "กรอกจำนวนเงิน",
      send_receipt: "ส่งใบเสร็จ (QR Code)",
      no_transactions: "ยังไม่มีประวัติการทำธุรกรรม",
      home_menu:             "คุณต้องการทำอะไร?",
      no_addresses:          "คุณยังไม่มีที่อยู่ฝากเงิน",
      your_addresses_count:  "คุณมี {{count}} ที่อยู่ฝากเงิน:",
      select_address_delete: "เลือกที่อยู่เพื่อที่จะลบ:",
      address_deleted:       "✅ ลบที่อยู่เรียบร้อยแล้ว",
    },
    ja: {
      welcome: "GhostTrail へようこそ 👻",
      home: "🏠 ホーム",
      portfolio: "💼 ポートフォリオ",
      explore: "🔎 探索",
      transfer: "💸 送金",
      error: "❗ エラーが発生しました。後でもう一度お試しください。",
      withdrawal_success: "✅ 出金成功！",
      choose_currency: "通貨を選択してください",
      enter_address: "送金先アドレスを入力してください",
      enter_amount: "送金金額を入力してください",
      send_receipt: "領収書 (QRコード) を送信",
      no_transactions: "取引履歴がありません。",
      home_menu:             "何をしますか？",
      no_addresses:          "まだ入金アドレスがありません。",
      your_addresses_count:  "{{count}} 件の入金アドレスがあります：",
      select_address_delete: "削除するアドレスを選択してください：",
      address_deleted:       "✅ アドレスが削除されました。",
    },
    ko: {
      welcome: "GhostTrail에 오신 것을 환영합니다 👻",
      home: "🏠 홈",
      portfolio: "💼 포트폴리오",
      explore: "🔎 탐색",
      transfer: "💸 송금",
      error: "❗ 오류가 발생했습니다. 잠시 후 다시 시도해주세요.",
      withdrawal_success: "✅ 출금 성공!",
      choose_currency: "통화를 선택하세요",
      enter_address: "수신 주소를 입력하세요",
      enter_amount: "송금할 금액을 입력하세요",
      send_receipt: "영수증 (QR 코드) 보내기",
      no_transactions: "거래 내역이 없습니다.",
      home_menu:             "무엇을 하시겠습니까?",
      no_addresses:          "아직 입금 주소가 없습니다.",
      your_addresses_count:  "{{count}}개의 입금 주소가 있습니다:",
      select_address_delete: "삭제할 주소를 선택하세요:",
      address_deleted:       "✅ 주소가 삭제되었습니다.",
    }
  }
  
  const t = (lang, key) => {
    if (!languages[lang]) lang = 'en'
    return languages[lang][key] || languages['en'][key] || key
  }
  
  module.exports = { t }